const questions = [
  { text: 'Your perfect weekend suddenly becomes completely free. What sounds most exciting?', answers: ['Following a beautiful, unplanned detour', 'Making something with your hands', 'Gathering your favorite people', 'Finding a quiet place no one knows about'] },
  { text: 'Someone gives you a mysterious locked box. What do you do first?', answers: ['Look for the hidden story behind it', 'Study how the lock was made', 'Ask who it belonged to', 'Try the boldest way to open it'] },
  { text: 'You walk into a room where nobody knows you. What naturally happens?', answers: ['A curious conversation starts nearby', 'You find the most interesting detail', 'People seem to relax around you', 'You quietly take in the whole room'] },
  { text: 'A friend asks for advice about a difficult situation. What is your instinct?', answers: ['Help them see a hopeful possibility', 'Ask questions until the truth is clear', 'Remind them they do not have to face it alone', 'Tell them the honest thing they need to hear'] },
  { text: 'Which kind of place feels most like a secret invitation?', answers: ['A sunlit garden after rain', 'A candlelit library with a locked door', 'A lively market in a city you have never seen', 'A moonlit shore with no footprints'] },
  { text: 'You have one free ticket for tonight. Where does your instinct take you?', answers: ['Somewhere with music and new faces', 'A rare film or performance', 'A last-minute trip out of town', 'A small gathering with someone fascinating'] },
  { text: 'When plans change at the very last minute, you usually...', answers: ['Turn the surprise into an adventure', 'Pause and make a better plan', 'Make sure everyone feels okay first', 'Take the lead and choose a new direction'] },
  { text: 'What would you save from a beautiful old house?', answers: ['A handwritten letter', 'A strange little painting', 'The key to an unknown room', 'A table where everyone once gathered'] },
  { text: 'Your dreams have left a symbol in your mind. Which feels most familiar?', answers: ['A flame that never goes out', 'A door opening onto stars', 'A river changing its course', 'A crown hidden beneath velvet'] },
  { text: 'At the end of a long day, what kind of feeling restores you?', answers: ['The glow of having made progress', 'The hush of being completely yourself', 'The warmth of being understood', 'The thrill of one more beautiful surprise'] }
];
const gems = {
  ruby:{name:'RUBY',title:'The Passionate Leader',energy:'Bold · Powerful · Fearless',description:'You carry a vivid, unmistakable energy that moves a room before you say a word. You chase what matters with devotion and protect the people lucky enough to be yours. There is courage in your warmth and a rare certainty in the way you keep going.',traits:['Confident','Fearless','Loyal','Ambitious','Protective','Magnetic'],mbti:'ENTJ · ENFJ · ESTP',best:'Citrine',bestCopy:'Joy brings out your brightest fire.',bad:'Obsidian',badCopy:'Too much silence can dim your spark.',ratings:[5,2,3,4,2],quote:'Your fire was never meant to be hidden.',color:'#a52c5c'},
  amethyst:{name:'AMETHYST',title:'The Mystic Dreamer',energy:'Creative · Intuitive · Imaginative',description:'Your inner world is vast, luminous, and entirely your own. You notice the poetry in ordinary moments and trust the quiet signals others miss. Your imagination is not an escape; it is the way you discover what is true.',traits:['Creative','Intuitive','Dreamy','Artistic','Curious','Deep'],mbti:'INFP · INFJ · ENFP',best:'Opal',bestCopy:'A kindred spirit for your kaleidoscope mind.',bad:'Sapphire',badCopy:'Rules can feel too small for your visions.',ratings:[3,5,4,3,4],quote:'The most beautiful things are often sensed first.',color:'#754e9f'},
  aquamarine:{name:'AQUAMARINE',title:'The Free Spirit',energy:'Peaceful · Adventurous · Refreshing',description:'You move through life with the refreshing grace of water, finding possibility in every change of course. Freedom matters to you, but so does the peace you create wherever you land. Your optimism makes the unknown feel like an invitation.',traits:['Calm','Adventurous','Open-minded','Flexible','Optimistic','Relaxed'],mbti:'ENFP · ISFP · ESFP',best:'Rose Quartz',bestCopy:'Tender connection gives your freedom a home.',bad:'Garnet',badCopy:'Intensity can feel like a closed door.',ratings:[3,3,2,5,3],quote:'Where you wander, wonder follows.',color:'#4b9ca3'},
  sapphire:{name:'SAPPHIRE',title:'The Wise Strategist',energy:'Elegant · Intelligent · Thoughtful',description:'You have the rare gift of seeing beneath the surface. Before you move, you listen; before you judge, you understand. Your calm intelligence is quietly magnetic, and people trust the clarity you bring to complicated things.',traits:['Wise','Analytical','Elegant','Logical','Observant','Thoughtful'],mbti:'INTJ · INFJ · ISTJ',best:'Emerald',bestCopy:'Warmth softens your beautifully precise mind.',bad:'Citrine',badCopy:'Noise can interrupt your clearest thoughts.',ratings:[4,4,2,2,1],quote:'Still waters hold the deepest blue.',color:'#285d9b'},
  emerald:{name:'EMERALD',title:'The Heart Healer',energy:'Growth · Harmony · Compassion',description:'You make the world around you feel safer, softer, and more possible. People bring you their unfinished stories because you know how to hold them without trying to rewrite them. Your steady kindness is a form of quiet strength.',traits:['Caring','Patient','Supportive','Balanced','Loyal','Understanding'],mbti:'ENFJ · ISFJ · INFJ',best:'Aquamarine',bestCopy:'Shared ease makes both your spirits bloom.',bad:'Ruby',badCopy:'A little less force lets your care breathe.',ratings:[3,2,5,3,1],quote:'Your kindness is a garden that remembers every name.',color:'#168268'},
  opal:{name:'OPAL',title:'The Unique Spark',energy:'Colorful · Expressive · Unpredictable',description:'You were never meant to fit into a single shade. Your ideas arrive from unexpected angles, and your presence changes color depending on the light. The world feels more alive around your curiosity and playful originality.',traits:['Unique','Expressive','Creative','Spontaneous','Curious','Adaptable'],mbti:'ENTP · ENFP · ESFP',best:'Amethyst',bestCopy:'Imagination recognizes imagination.',bad:'Obsidian',badCopy:'You need room to change and shine.',ratings:[3,4,4,4,5],quote:'There is no ordinary angle from which to see you.',color:'#bd6686'},
  rose:{name:'ROSE QUARTZ',title:'The Gentle Heart',energy:'Love · Warmth · Connection',description:'You understand that tenderness is not fragility, but a beautiful kind of courage. You listen with your whole heart and make honesty feel like a soft place to land. The connections you nurture are the most lasting treasures in your life.',traits:['Romantic','Gentle','Warm','Compassionate','Affectionate','Sensitive'],mbti:'INFP · ISFP · ENFJ',best:'Emerald',bestCopy:'Shared care gives your love somewhere to grow.',bad:'Obsidian',badCopy:'Distance leaves too much unsaid.',ratings:[2,3,5,3,1],quote:'The rarest strength is a heart that stays open.',color:'#c87883'},
  citrine:{name:'CITRINE',title:'The Sunshine Spirit',energy:'Joy · Energy · Inspiration',description:'You have a way of turning a room toward the light. Your enthusiasm is generous, contagious, and never as simple as it first appears: you notice what people need in order to feel alive. Wherever you go, possibility seems to follow.',traits:['Cheerful','Energetic','Social','Positive','Inspiring','Fun'],mbti:'ESFP · ENFP · ENTP',best:'Ruby',bestCopy:'Bold dreams make your joy burn brighter.',bad:'Sapphire',badCopy:'Overthinking can steal the golden hour.',ratings:[4,2,4,4,5],quote:'You are proof that joy can be a force of nature.',color:'#d39334'},
  obsidian:{name:'OBSIDIAN',title:'The Silent Guardian',energy:'Mystery · Strength · Protection',description:'There are entire constellations inside you that few people ever get to see. You are discerning with your trust, but unwavering once it is given. Your quiet presence carries a gravity that makes others feel both curious and protected.',traits:['Independent','Mysterious','Strong','Private','Resilient','Protective'],mbti:'ISTP · INTJ · ISTJ',best:'Sapphire',bestCopy:'A thoughtful equal understands your silence.',bad:'Citrine',badCopy:'Brightness needs not always be an audience.',ratings:[5,5,1,2,2],quote:'Some lights are made to glow from the dark.',color:'#4f566e'},
  garnet:{name:'GARNET',title:'The Hidden Fire',energy:'Passion · Loyalty · Determination',description:'Your strength burns steadily, without needing an audience. You are dependable in the moments that matter and deeply committed to the people and promises you choose. Beneath your composed surface lives an extraordinary, enduring fire.',traits:['Determined','Passionate','Reliable','Brave','Focused','Devoted'],mbti:'ISTJ · ISFP · ESTJ',best:'Ruby',bestCopy:'A fellow flame understands your devotion.',bad:'Aquamarine',badCopy:'Too much drifting tests your patience.',ratings:[4,3,3,4,2],quote:'The quietest flame can last the longest.',color:'#a33b37'}
};
const gemKeys=Object.keys(gems);let current=0;let selectionSignature=0;let scores=Object.fromEntries(gemKeys.map(k=>[k,0]));
const answerGemSets=questions.map((_,questionIndex)=>Array.from({length:4},(_,choiceIndex)=>{const primary=(questionIndex*3+choiceIndex*2)%gemKeys.length;return[gemKeys[primary],gemKeys[(primary+3)%gemKeys.length],gemKeys[(primary+6)%gemKeys.length]]}));
const $=id=>document.getElementById(id);function show(id){document.querySelectorAll('.view').forEach(v=>v.hidden=true);$(id).hidden=false;$(id).classList.add('active');window.scrollTo(0,0)}
function renderQuestion(){const q=questions[current];$('question-number').textContent=String(current+1).padStart(2,'0');$('progress-bar').style.width=`${(current+1)*10}%`;$('question-title').textContent=q.text;$('answers').innerHTML=q.answers.map((a,i)=>`<button class="answer" data-choice="${i}"><b>${String.fromCharCode(65+i)}</b>${a}</button>`).join('');document.querySelectorAll('.answer').forEach(button=>button.addEventListener('click',()=>choose(Number(button.dataset.choice))))}
function choose(choice){const set=answerGemSets[current][choice];set.forEach((gem,index)=>{scores[gem]+=index===0?3:index===1?2:1});selectionSignature+=(choice+1)*(current+1);current++;if(current<questions.length){renderQuestion()}else renderResult()}
function playRevealChime(){const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)return;const audioContext=new AudioContext();const notes=[523.25,659.25,783.99];const startTime=audioContext.currentTime;notes.forEach((frequency,index)=>{const oscillator=audioContext.createOscillator();const gain=audioContext.createGain();oscillator.type='sine';oscillator.frequency.value=frequency;gain.gain.setValueAtTime(0,startTime+index*.16);gain.gain.linearRampToValueAtTime(.11,startTime+index*.16+.03);gain.gain.exponentialRampToValueAtTime(.001,startTime+index*.16+.75);oscillator.connect(gain);gain.connect(audioContext.destination);oscillator.start(startTime+index*.16);oscillator.stop(startTime+index*.16+.8)});setTimeout(()=>audioContext.close(),1800)}
function renderResult(){const highestScore=Math.max(...gemKeys.map(k=>scores[k]));const topGems=gemKeys.filter(k=>scores[k]===highestScore);const key=topGems[selectionSignature%topGems.length];const gem=gems[key];$('report-card').style.setProperty('--gem-glow',gem.color);$('gem-name').textContent=gem.name;$('gem-title').textContent=gem.title;$('gem-energy').textContent=gem.energy;$('gem-description').textContent=gem.description;$('gem-traits').innerHTML=gem.traits.map(t=>`<span>${t}</span>`).join('');$('gem-mbti').textContent=gem.mbti;$('best-match').textContent=gem.best;$('best-copy').textContent=gem.bestCopy;$('bad-match').textContent=gem.bad;$('bad-copy').textContent=gem.badCopy;$('gem-quote').textContent=`“${gem.quote}”`;$('result-crystal').style.background=`linear-gradient(130deg,#f2a3a8,${gem.color} 42%,#18121f 78%,${gem.color})`;$('result-crystal').style.boxShadow=`0 0 75px ${gem.color}`;$('rating-list').innerHTML=['Confidence','Mystery','Romance','Adventure','Chaos'].map((n,i)=>`<div class="rating"><span>${n}</span><span class="stars">${'★'.repeat(gem.ratings[i])}${'☆'.repeat(5-gem.ratings[i])}</span></div>`).join('');show('result-view');playRevealChime()}
function startQuiz(){current=0;selectionSignature=0;scores=Object.fromEntries(gemKeys.map(k=>[k,0]));show('quiz-view');renderQuestion()}
$('begin-button').addEventListener('click',()=>show('preview-view'));$('preview-button').addEventListener('click',startQuiz);$('restart-button').addEventListener('click',()=>show('preview-view'));$('share-button').addEventListener('click',async()=>{const text=`I discovered my gem on What Gem Are You: ${$('gem-name').textContent} - ${$('gem-title').textContent}`;if(navigator.share)await navigator.share({title:'What Gem Are You?',text});else{await navigator.clipboard.writeText(text);$('share-button').innerHTML='Copied to clipboard <span>✦</span>';setTimeout(()=>$('share-button').innerHTML='Share your gem <span aria-hidden="true">↗</span>',1800)}});